/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medactema14.practica_intermodular;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class JFramePractica_intermodular extends javax.swing.JFrame {

    
    public JFramePractica_intermodular() {
        initComponents();
        Conexionbbdd conexionbbdd = new Conexionbbdd();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlTemperatura = new javax.swing.JLabel();
        jlDistancia = new javax.swing.JLabel();
        jLRadio = new javax.swing.JLabel();
        jComposicion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bMarte = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bSaturno = new javax.swing.JButton();
        bUrano = new javax.swing.JButton();
        bNeptuno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jDia = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jnumeroSatelite = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();

        jLabel12.setText("jLabel8");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de planeta");

        jLabel2.setText("Radio");

        jLabel3.setText("Temperatura");

        jLabel4.setText("Distancia");

        jLabel5.setText("Composicion");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SISTEMA SOLAR");

        jlTipo.setText(".");

        jlTemperatura.setText(".");

        jlDistancia.setText(".");

        jLRadio.setText(".");

        jComposicion.setText("74%Hidrogeno,24%Helio,2% Otros");

        jLabel8.setText("AUTOR: DANIEL COLLADO BRAVO");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\solpequeño2.jpg")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("PRÁCTICA INTERMODULAR - SISTEMA SOLAR");

        bMarte.setText("Marte");
        bMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMarteActionPerformed(evt);
            }
        });

        jButton2.setText("Jupiter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bSaturno.setText("Saturno");
        bSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaturnoActionPerformed(evt);
            }
        });

        bUrano.setText("Urano");
        bUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUranoActionPerformed(evt);
            }
        });

        bNeptuno.setText("Neptuno");
        bNeptuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNeptunoActionPerformed(evt);
            }
        });

        jButton1.setText("Tierra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Venus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mercurio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel11.setText("Sol");

        jLabel13.setText("Tipo de Estrella");

        jLabel14.setText("G2V");

        jLabel15.setText("Radio (km)");

        jLabel16.setText("696340");

        jLabel17.setText("Temperatura");

        jLabel18.setText("5500");

        jLabel19.setText("Distancia Media");

        jLabel20.setText("149,6");

        jLabel21.setText("Periodo Orbita(dias)");

        jDia.setText(".");

        jLabel22.setText("Nombre del planeta");

        jNombre.setText(".");

        jLabel23.setText("Numero de saltelites");

        jnumeroSatelite.setText(".");

        Imagen.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComposicion)
                                    .addComponent(jLabel20)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bSaturno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bUrano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bNeptuno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bMarte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)))
                                .addGap(18, 18, 18)
                                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel22)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnumeroSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(bMarte)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSaturno)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bUrano)
                                .addComponent(bNeptuno)
                                .addComponent(jButton2))))
                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jnumeroSatelite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * Maneja el evento de acción del botón de Marte.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Marte 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void bMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMarteActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Martepequeño.jpg");
        Conexionbbdd conexion = new Conexionbbdd();
        String[] datosMarte =  conexion.conectarConsultarMarte();
        jNombre.setText("Marte");
        jLRadio.setText(datosMarte[0]); 
        jlTipo.setText(datosMarte[4]);
        jlTemperatura.setText(datosMarte[3]);
        jlDistancia.setText(datosMarte[1]);
        jDia.setText(datosMarte[2]);
        jnumeroSatelite.setText(datosMarte[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_bMarteActionPerformed
    /**
     * Maneja el evento de acción del botón de Venus.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Venus 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Venuspequeño.png");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosVenus =  conexion.conectarConsultarVenus();
        jNombre.setText("Venus");
        jLRadio.setText(datosVenus[0]); 
        jlTipo.setText(datosVenus[4]);
        jlTemperatura.setText(datosVenus[3]);
        jlDistancia.setText(datosVenus[1]);
        jDia.setText(datosVenus[2]);
        jnumeroSatelite.setText(datosVenus[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_jButton3ActionPerformed

     /**
     * Maneja el evento de acción del botón de Tierra.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Tierra 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Tierrapequeño.jpg");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosTierra =  conexion.conectarConsultarTierra();
        jNombre.setText("Tierra");
        jLRadio.setText(datosTierra[0]); 
        jlTipo.setText(datosTierra[4]);
        jlTemperatura.setText(datosTierra[3]);
        jlDistancia.setText(datosTierra[1]);
        jDia.setText(datosTierra[2]);
        jnumeroSatelite.setText(datosTierra[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
     * Maneja el evento de acción del botón de Mercurio
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Mercurio 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Mercuriopequeño.jpg");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosMercurio =  conexion.conectarConsultarMercurio();
        jNombre.setText("Mercurio");
        jLRadio.setText(datosMercurio[0]); 
        jlTipo.setText(datosMercurio[4]);
        jlTemperatura.setText(datosMercurio[3]);
        jlDistancia.setText(datosMercurio[1]);
        jDia.setText(datosMercurio[2]);
        jnumeroSatelite.setText(datosMercurio[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_jButton4ActionPerformed

     /**
     * Maneja el evento de acción del botón de Saturno.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Saturno 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void bSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaturnoActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Saturnopequeño.png");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosSaturno =  conexion.conectarConsultarSaturno();
        jNombre.setText("Saturno");
        jLRadio.setText(datosSaturno[0]); 
        jlTipo.setText(datosSaturno[4]);
        jlTemperatura.setText(datosSaturno[3]);
        jlDistancia.setText(datosSaturno[1]);
        jDia.setText(datosSaturno[2]);
        jnumeroSatelite.setText(datosSaturno[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_bSaturnoActionPerformed

     /**
     * Maneja el evento de acción del botón de Urano
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Urano 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void bUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUranoActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Uranopequeño.jpg");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosUrano =  conexion.conectarConsultarUrano();
        jNombre.setText("Urano");
        jLRadio.setText(datosUrano[0]); 
        jlTipo.setText(datosUrano[4]);
        jlTemperatura.setText(datosUrano[3]);
        jlDistancia.setText(datosUrano[1]);
        jDia.setText(datosUrano[2]);
        jnumeroSatelite.setText(datosUrano[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_bUranoActionPerformed

     /**
     * Maneja el evento de acción del botón de Neptuno.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Neptuno 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void bNeptunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNeptunoActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Neptunopequeño.jpg");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosNeptuno =  conexion.conectarConsultarNeptuno();
        jNombre.setText("Neptuno");
        jLRadio.setText(datosNeptuno[0]); 
        jlTipo.setText(datosNeptuno[4]);
        jlTemperatura.setText(datosNeptuno[3]);
        jlDistancia.setText(datosNeptuno[1]);
        jDia.setText(datosNeptuno[2]);
        jnumeroSatelite.setText(datosNeptuno[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_bNeptunoActionPerformed

     /**
     * Maneja el evento de acción del botón de Jupiter.
     * Este evento se ejecutara cuando en la interfaz le demos al boton de Jupiter 
     * Lo que hace es que todos los datos que hemos sacado mediante la consulta los labels se le cambiaran los textos acorde a lo que este en la base de datos
     * Ademas busca la foto que esta guardada en la carpeta de resource y la pone en el label 
     * @param evt  el evento de acción que desencadenó este método
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ImageIcon foto = new ImageIcon("C:\\Users\\Usuario\\Desktop\\Practica_Intermodular\\practica_intermodular\\src\\main\\resources\\Jupiterpequeño.jpg");
         Conexionbbdd conexion = new Conexionbbdd();
        String[] datosJupiter =  conexion.conectarConsultarJupiter();
        jNombre.setText("Jupiter");
        jLRadio.setText(datosJupiter[0]); 
        jlTipo.setText(datosJupiter[4]);
        jlTemperatura.setText(datosJupiter[3]);
        jlDistancia.setText(datosJupiter[1]);
        jDia.setText(datosJupiter[2]);
        jnumeroSatelite.setText(datosJupiter[7]);
        Imagen.setIcon(foto);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePractica_intermodular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePractica_intermodular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePractica_intermodular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePractica_intermodular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePractica_intermodular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton bMarte;
    private javax.swing.JButton bNeptuno;
    private javax.swing.JButton bSaturno;
    private javax.swing.JButton bUrano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jComposicion;
    private javax.swing.JLabel jDia;
    private javax.swing.JLabel jLRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jlDistancia;
    private javax.swing.JLabel jlTemperatura;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jnumeroSatelite;
    // End of variables declaration//GEN-END:variables
}
